[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  
  # ✅ CONFIGURAR ESTAS EN NETLIFY DASHBOARD
  # PUBLIC_SUPABASE_URL = "https://tu-proyecto.supabase.co"
  # PUBLIC_SUPABASE_ANON_KEY = "eyJ..."

# Redirects para tus rutas específicas de Kamasex
[[redirects]]
  from = "/productos/:slug"
  to = "/productos/:slug"
  status = 200

[[redirects]]
  from = "/categoria/:categoria"
  to = "/categoria/:categoria"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Páginas principales
[[redirects]]
  from = "/carrito"
  to = "/carrito/index.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Fallback 404 personalizado
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers para performance
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"